pychapp:
  env: dev # or prod
  secret: "Pls68m35-oXRfEo1HAPKPyjI3SPiC-3UP140vn1xisU="
  rsa_secret: "change_it"

  rest:
    host: '0.0.0.0'
    port: 8000

  mongo:
    con_link: mongodb://pwnstand.lc:27017/
    db: pychapp